---

- name: Deploy Playbook
  hosts: all
  tasks:

    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Install gunicorn
      become: true
      apt:
        name: gunicorn3
        state: present

    - name: Install supervisor
      become: true
      apt:
        name: supervisor
        state: present

    - name: Install nginx
      become: true
      apt:
        name: nginx
        state: present

    # Commands to install virtualenv
    #- name: Install virtualenv
    #  become: true
    #  apt:
    #    name: virtualenv
    #   state: present

    #- name: Install python3-venv
    #  become: true
    #  apt:
    #    name: python3-venv
    #    state: present

    - name: Ensure Pip is installed.
      become: true
      package:
        name: python3-pip
        state: present

    # Didn't need to setup virtualenv
    #- name: Creating virualenv
    #  become: true
    #  shell: python3 -m venv /home/ubuntu/env

    # Why not root?
    #- name: Activate virualenv
    #  shell: /bin/bash -c "source /home/ubuntu/env/bin/activate"

    - name: Install specified python requirements
      become: true
      pip:
        executable: pip3
        requirements: /home/ubuntu/DLTinMachine/requirements.txt
        extra_args: --no-cache-dir

    # Install opencv using apt-get as well (libraries installed with pip were causing issues)
    - name: Install python3-opencv
      become: true
      apt:
        name: python3-opencv
        state: present

    - name: Copy gunicorn.conf to the appropriate location
      become: yes
      copy:
        src: /home/ubuntu/DLTinMachine/conf.d/gunicorn.conf
        #src: ../conf.d/gunicorn.conf
        dest: /etc/supervisor/conf.d
        remote_src: yes

    - name: Copy django.conf (nginx) to sites-enabled
      become: yes
      copy:
        src: /home/ubuntu/DLTinMachine/conf.d/django.conf
        #src: ../conf.d/django.conf
        dest: /etc/nginx/sites-available
        remote_src: yes

    - name: Copy nginx.conf (nginx) to main location
      become: yes
      copy:
        src: /home/ubuntu/DLTinMachine/conf.d/nginx.conf
        #src: ../conf.d/nginx.conf
        dest: /etc/nginx/nginx.conf
        remote_src: yes

    - name: Create a symbolic link for django.conf
      become: yes
      file:
        src: /etc/nginx/sites-available/django.conf
        dest: /etc/nginx/sites-enabled/django.conf
        state: link

    - name: Reread the supervisor configuration
      become: yes
      shell: supervisorctl reread

    - name: Update the supervisor configuration
      become: yes
      shell: supervisorctl update

    - name: Reload nginx configuration
      become: yes
      shell: nginx -s reload